[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

# Config específica para la Function "api"
[functions.api]
  included_files = ["api/**", "data/**"]

# Enruta TODO hacia la Function (incluye /docs, /books, etc.)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
