[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

[functions.api]
  # TODO: incluye todo lo que tu app lee en runtime
  included_files = [
    "api/**",
    "controllers/**",
    "service/**",
    "data/**"
  ]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
