[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

# Enruta TODO a la Function (incluye /docs, /books, etc.)
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
