[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

# Incluye archivos no-JS dentro del bundle de la Function "api"
[[functions]]
  name = "api"
  included_files = ["api/openapi.yaml", "data/**"]
