[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

[functions.api]
  included_files = ["api/**", "controllers/**", "service/**", "data/**"]

# 👇 especial para la raíz
[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/docs"
  status = 200

# catch-all para todo lo demás
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
