[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["express","oas3-tools","serverless-http"]

[functions.api]
  included_files = ["api/**", "controllers/**", "service/**", "data/**"]

# rutas explícitas primero
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/api/health"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/api/docs"
  status = 200

[[redirects]]
  from = "/docs/*"
  to = "/.netlify/functions/api/docs/:splat"
  status = 200

# raíz → function (la app redirige a /docs)
[[redirects]]
  from = "/"
  to = "/.netlify/functions/api/"
  status = 200

# catch-all para el resto de la API
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
